apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: schemas
  namespace: kafka
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: cp
        image: solsson/kafka-cp@sha256:89e5b3b326bf8ef888efa9501cd22fb941ca7b5ccef8dfc2f44a1e218f4427e1
        env:
        - name: SCHEMA_REGISTRY_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/schema-registry/log4j.properties
        command:
        - schema-registry-start
        - /etc/schema-registry/schema-registry.properties
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/schema-registry
      volumes:
      - name: config
        configMap:
          name: confluent-config
